### PR TITLE
add DSS as an indexer endpoint

### PR DESCRIPTION
**Pull request by willscott**

### CODE REVIEW

**Comment by TorfinnOlsen** [comment]
MicrosoftTeams-image (6)
DSS_Logo_Exports_DSS_Logo_White


Logos for DSS!

**Comment by willscott** [comment]
do you have an SVG?

**Comment by marshyonline** [comment]
DSS_Logo_Exports_DSS_Logo_Blue
DSS_Logo_Exports_DSS_Logo_White
DSS_Logo_Exports_DSS_Icon_Blue
DSS_Logo_Exports_DSS_Icon_White

**Comment by marshyonline** [comment]
Full logos and Icons in SVG for you :)

**Pull request merged**
